### ISSUE TITLE
How to fake migrations?

### ISSUE THREAD

**Issue by yaccz** [jtdaugherty/dbmigrations#18]
Sometimes it happens that migrations are created for an existing database or are migrated from another migrations system.

In these cases it is necessary to be able to fake the migrations so only the migration state data are written but no migration is actually executed to get the database and migration state information into consistent state.

How to do this with dbmigrations?

**Comment by jtdaugherty** [comment]
For that situation, I suggest dumping the database schema built from an older migrations system and put it into the first migration in a `dbmigrations` setup.  The `dbmigrations` package doesn't provide a facility for migrating from other migration-management systems.  Alternatively, you can do the following to accomplish this manually:

* Create a table in your database as follows:
```
CREATE TABLE installed_migrations (migration_id TEXT);
```
* For each migration that is already "installed" in the schema, insert a row into the `installed_migrations` with that migration's name as the `migration_id` value.  For this to work, the inserted `migration_id` value must be the `basename` of some migration file (e.g. `foo.txt` becomes `foo` in the table).

**Comment by jtdaugherty** [comment]
I'm closing this ticket because I don't have any plans to support this in `dbmigrations`, but I am happy to continue discussing this here if you need assistance. Thanks!

**Comment by pbrisbin** [comment]
In case anyone else comes along looking for this, I came up with the following script that marks a database as migrated with any existing migration files -- without actually taking any actions on the DB, of course:

```sh
#!/bin/sh
set -e

DBM_DATABASE=postgres://the-db-to-mark

# Using an empty directory makes moo-upgrade *only* initialize the
# installed_migrations table for us.
DBM_MIGRATION_STORE=$(mktemp -d)

export DBM_DATABASE
export DBM_MIGRATION_STORE

stack exec -- moo-postgresql upgrade

for path in db/migrations/*.txt; do
  name=$(basename "$path" .txt)

  psql "$DBM_DATABASE" <<EOM
    INSERT INTO installed_migrations (migration_id)
    SELECT '$name' WHERE NOT EXISTS (
      SELECT migration_id FROM installed_migrations WHERE migration_id = '$name'
    );
EOM
done
```
