### ISSUE TITLE
dbmigrations-0.8.1 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [jtdaugherty/dbmigrations#19]
It appears there are some modules missing from the release tarball: http://hydra.cryp.to/build/574168/nixlog/2/raw.

**Comment by jtdaugherty** [comment]
Yikes! I'm working on fixing the cabal file now and will update here when it's fixed.

**Comment by jtdaugherty** [comment]
`0.8.2` is now on Hackage and includes the fix for this issue.

**Comment by jtdaugherty** [comment]
Thanks for the report!
