### ISSUE TITLE
Support `moo --version`

### ISSUE THREAD

**Issue by creswick** [jtdaugherty/dbmigrations#21]
It's not easy to tell which version of dbmigrations you're using, which makes reporting bugs more difficult.

Supporting the standard version command line flags would be pretty nice, and given the nature of the tool, it would be great to also support `--numeric-version`.

Expected behavior:

``` bash
# This first one could be more verbose:
$ moo --version
dbmigrations 0.9

# This should report *exactly* the version number, and nothing else, as it is intended to be parsed by the cabal version number parser; and as such, can more easily be added as a build-tool dependency.
$ moo --numeric-version
0.9
```

See ghc --version and ghc --numeric-version for more examples.

**Comment by jtdaugherty** [comment]
Since this package is no longer maintained, I'd like to mark the GitHub repository as read-only. I'm closing this ticket as part of that change. This package is now marked as deprecated on Hackage; see the maintenance note in the README if you're interested in taking over maintenance.
