### ISSUE TITLE
Installation fails if pg_config is not present

### ISSUE THREAD

**Issue by akshaymankar** [jtdaugherty/dbmigrations#29]
I'm trying to use dbmigrations with sqlite. It should not require postgresql to be installed my system. 
Or am I missing something?

**Comment by jtdaugherty** [comment]
This issue comes up for users of other backends, too, and it's something I'd like to address.  You can read some existing discussion on https://github.com/jtdaugherty/dbmigrations/issues/28, and I'll close this as a duplicate - please pick things up there.  Thank you!
