### ISSUE TITLE
Document why the cli tool is called "moo"

### ISSUE THREAD

**Issue by robertmassaioli** [jtdaugherty/dbmigrations#37]
Is it just a fun name, an acronym, a bacronym? Where did it come from? The suspense is killing me. It's been 12 years, the people have waited long enough. 😛

**Comment by jtdaugherty** [comment]
Hah! Well, let's see if I can remember. At the time I was writing the library, I wanted a tool name that was very short and memorable. Tool names with "db" in the name felt natural, but they too easily clashed with existing tool names or were too generic. I also really wanted to avoid the all-to-common tendency to just slap an "h" on the tool name as so many Haskell programmers do. (Namespaces are hard, especially when they are global.) In a moment of what is probably poor judgment, I chose "moo" as something that was short, easy to type (to me), memorable (ish?), and was unlikely to collide with any existing tool names. Granted, looking back, I'm not especially proud of the choice. But there you go. 😊

**Comment by robertmassaioli** [comment]
Thanks for resolving this once and for all.
