### ISSUE TITLE
Since dbmigrations 2.1.0, migrations with . in the name are truncated

### ISSUE THREAD

**Issue by wduncanfraser** [jtdaugherty/dbmigrations#40]
Since dbmigrations 2.1.0, migrations with . in the name, such as 2018-11-13_20-18-16_v0.1.0.txt are truncated at the last non-extension . and interpreted like 2018-11-13_20-18-16_v0.1

As a test, renaming to 2018-11-13_20-18-16_v0.1.txt results in an interpreted migration name of 2018-11-13_20-18-16_v0 Confirmed building dbmigrations-postgresql with a constraint of dbmigrations==2.0.0 resolves the issue.

Obviously, this breaks all existing migration stores where . were used in the migration names.

**Comment by jtdaugherty** [comment]
Thanks for reporting this!

**Comment by jtdaugherty** [comment]
Since this package is no longer maintained, I'd like to mark the GitHub repository as read-only. I'm closing this ticket as part of that change. This package is now marked as deprecated on Hackage; see the maintenance note in the README if you're interested in taking over maintenance.
