### ISSUE TITLE
aeson <2 dependency relaxation: What would it take to remove that restriction?

### ISSUE THREAD

**Issue by robertmassaioli** [jtdaugherty/dbmigrations#44]
What would it take to make dbmigrations support v2 of the aeson library?

**Comment by jtdaugherty** [comment]
`master` builds with `aeson` 2.0 and above. Have you tried that?

(For completeness, as mentioned in the README: I do not maintain this package any longer.)

**Comment by jtdaugherty** [comment]
Since this package is no longer maintained, I'd like to mark the GitHub repository as read-only. I'm closing this ticket as part of that change. This package is now marked as deprecated on Hackage; see the maintenance note in the README if you're interested in taking over maintenance.
