### ISSUE TITLE
Unrecognized field found when running migration

### ISSUE THREAD

**Issue by BarbDMC** [jtdaugherty/dbmigrations#45]
When I run the following migration with the command `dotenv 'moo-postgresql upgrade'`:

```
Description: Sample Migration 
Created: 2024-01-30 14:21:56.815803195 UTC 
Depends:  
Apply: | 
  SELECT * FROM table;
```
  
 I have the following error:
 
 `There were errors in the migration store:
  There was an error loading a migration: Could not parse migration migrations/foo.txt: Error in "migrations/foo.txt": unrecognized field found`
  
 The workaround that I found was to remove the decimal values after the seconds (`.815803195`) and, remove 'UTC' from the Created field like this:
 
```
Description: Sample Migration
Created: 2024-01-30 14:21:56
Depends: create_new_table
Apply: |
  SELECT * FROM table;
```

**Comment by jtdaugherty** [comment]
Hi @BarbDMC, you might consider trying `master` which includes https://github.com/jtdaugherty/dbmigrations/pull/43.

**Comment by jtdaugherty** [comment]
Since this package is no longer maintained, I'd like to mark the GitHub repository as read-only. I'm closing this ticket as part of that change. This package is now marked as deprecated on Hackage; see the maintenance note in the README if you're interested in taking over maintenance.
